config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'

  devise_for :users

  # STATIC PAGES
  get 'help' => "static_pages#help"
  get 'about' => "static_pages#about"
  get 'contact' => "static_pages#contact"
  get "terms" => "static_pages#terms"
  get "privacy" => "static_pages#privacy"
  get "search" => "posts#search"


  # USERS
  resources :users, only: [:show, :edit, :update]

  #POSTS
  resources :posts, only: [:create, :new, :show, :index]

  #COMENTS
  resources :comments, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 140 }
  validates :content, presence: true

  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  has_one_attached :image

  has_many :posts

  has_many :comments


  def update_user_with_image(image, user_params)
    self.image.attach(image)
    self.update(user_params)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    user = comment.post.user
    post = comment.post
    if comment.save
      unless user == current_user
        CommentMailer.with(user: user, post: post).comment_mail.deliver_now
      end
      redirect_to post_path(post.id)
    end
  end


  def destroy
    comment = Comment.find(params[:id])
    post = comment.post
    comment.destroy
    if comment.destroyed?
      flash[:notice] = "Comment deleted"
    end
    redirect_to post_path(post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  #return list of posts
  def index
    #ask for an user with user_id, if its true, get it using a hash id as a key and params with the  value)
    if params[:user_id]
      user = User.find_by(id: params[:user_id])
      #get post of that single user(asigned already above) or just using user.posts
      @posts = Post.where({user_id: user.id})
      if user == current_user
        @page_title = "My Articles"
      else
        @page_title = "Articles written by #{user.name}"
      end
    else
      #if theres no user id show all posts of all users
      @posts = Post.all
      @page_title = "All Articles"
    end
  end

  def search
    keyword = params[:q]
    @posts = Post.where("title ILIKE ?", "%#{keyword}%")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "Article created!"
      redirect_to post_path(@post.id)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
    @comments = Comment.where(post_id: @post.id)
  end

private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def terms
  end

  def privacy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_user_with_image(params[:image], user_params)
      flash[:notice] = "Profile Updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

 private

   def user_params
     params.require(:user).permit(:name, :username, :location, :image)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.haml
.row
  .col-md-12
    .list-group-flush
      .d-fle.w-100.justify-content-between
        - @comments.each do |comment|
          .list-group-item.list-group-item-action
            = link_to @user.name, posts_path(user_id: @user.id)
            = comment.content
            %small.timestamp
              Posted
              = time_ago_in_words(comment.created_at)
              ago.
              %br
              = link_to 'Delete', comment_path(comment.id), :method => :delete

app/views/comments/_form.haml
%h6.comment What do you think about this article? Write a comment below!
= form_for @comment do |f|
  = render "devise/shared/error_messages", resource: @comment
  %br
  .form-group
    .pb-cmnt-textarea
      = f.text_area :content, class: "form-control", placeholder: "comment here!"
    %br
    = f.hidden_field :post_id, value: @post.id
    .actions
      = f.submit "Comment", class: "btn btn-primary"

app/views/layouts/_navbar.haml
%nav.navbar.fixed-top.navbar-expand-lg.navbar-light.bg-light.justify-content-between
  %a.navbar-brand(href="#")
    %img(src= "https://4.bp.blogspot.com/-8rpOtgXlYxU/WTa8a6ubDTI/AAAAAAAAf3E/IM-VwUXLlT4RQUV8w-Tgp7JQSRGlpPIqACLcB/s1600/diplomacia%25C2%25B43.jpg" width="30" height="30" alt=" ")
  %button.navbar-toggler(type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation")
    %span.navbar-toggler-icon
  %div.collapse.navbar-collapse#navbarNav
    %ul.navbar-nav
      %li.nav-item.active
        = link_to "Home", root_path, class: "nav-link"
      %li.nav-item
        = link_to "Help", help_path, class: "nav-link"
      %li.nav-item
        = link_to "About", about_path, class: "nav-link"
      - if user_signed_in?
        %li.nav-item
          = link_to "Articles", posts_path, class: "nav-link"
        %li.nav-item
          = link_to "Profile", user_path(current_user.id), class: "nav-link"
        %li.nav-item
          = link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link"
      - else
        = link_to "log in", new_user_session_path, class: "nav-link"
  %form.form-inline(action="/search")
    %input.form-control.mr-sm-2(type="search" name="q" placeholder="Search" aria-label="Search")
    %button.btn.btn-outline-success.my-2.my-sm-0(type="submit")
      Search

app/views/layouts/_notices.haml
.container
  - flash.each do |type, msg|
    - if type == "notice"
      .alert.alert-success.alert-dismissible.fade.show
        = msg
        %button.close{data: {dismiss: "alert"}, aria_label: "Close"}
          %span{aria_hidden: "true"}
            &times;
    -  if type == "alert"
      .alert.alert-danger.alert-dismissible.fade.show
        = msg
        %button.close{data: {dismiss: "alert"}, aria_label: "Close"}
          %span{aria_hidden: "true"}
            &times;
    - if type == "info"
      .alert.alert-info.alert-dismissible.fade.show
        = msg
        %button.close{data: {dismiss: "alert"}, aria_label: "Close"}
          %span{aria_hidden: "true"}
            &times;

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Iablog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "/layouts/navbar"
    = render "/layouts/notices"
    .container.main-page
      = yield
    = render "/shared/cookies"
    = render "/shared/footer"

app/views/posts/_comment.haml
%h4
  comment by
  = @username
%br
= @comment.content

app/views/posts/index.haml
.row
  .col-sm-6.offset-sm-3
    %h1.mb-1
      = @page_title
    .list-group
      .d-fle.w-100.justify-content-between
        - @posts.each do |post|
          .list-group-item.list-group-item-action
            = link_to post_path(post.id) do
              %h5.mb-1
                = post.title
            %small.timestamp
              Posted
              = time_ago_in_words(post.created_at)
              ago.
              %br
              %br
            .mb-1
              Author:
              = post.user.name
            %br

app/views/posts/new.haml
.row
  .col-md-6.offset-md-3
    %h1 Write an Article
    %br
    = form_for @post do |f|
      = render "devise/shared/error_messages", resource: @post
      .form-group
        = f.label :title
        = f.text_field :title, class: "form-control"
      %br
      .form-group
        = f.label :content
        = f.text_area :content, class: "form-control"
      %br
      .actions
        = f.submit "Create Article", class: "btn btn-primary"

app/views/posts/search.haml
.row
  .col-sm-6.offset-sm-3
    %h1 Searching results
    .list-group
      .d-fle.w-100.justify-content-between
        - @posts.each do |post|
          .list-group-item.list-group-item-action
            = link_to post_path(post.id) do
              %h5.mb-1
                = post.title

app/views/posts/show.haml
.row
  .col-md-6.offset-md-2
    .card.w-100
      .card-header
        = @post.title
      .card-body
        %blockquote.blockquote
          = @post.content
        %br
        %footer.blockquote-footer
          .mb-1
            Author:
            = @user.name
    %br
    %br
    = render partial: 'shared/infocard'
    %br
    %br
    = render partial: "comments/form"
    %h3
    All Comments
    (
    = @post.comments.size
    )
    %br
    = render partial: 'comments/comment'

app/views/shared/_cookies.html.haml
#cookies-toast.fixed-bottom.p-4
  .toast.bg-dark.text-white.w-100.mw-100(role="alert" data-autohide="false")
    .toast-body.p-4.d-flex.flex-column
      %h4 Cookie Warning
      %p This website stores data such as cookies to enable site functionality including analytics and personalization. By using this website, you automatically accept that we use cookies.
      .ml-auto
        #btnDeny.btn.btn-light.mr-3(type="button") Deny
        #btnAccept.btn.btn-light(type="button") Accept

app/views/shared/_footer.haml
.navbar.fixed-bottom.navbar-expand.navbar-dark.bg-dark
  .navbar-collapse.collapse.w-100.order-1.order-md-0.dual-collapse2
    %ul.navbar-nav.mr-auto
      %li.nav-item
        = link_to 'Contact', contact_path, class: "nav-link"
  .navbar-collapse.collapse.w-100.order-3.dual-collapse2
    %ul.navbar-nav.ml-auto
      %li.nav-item
        = link_to 'Terms & Conditions', terms_path, class: "nav-link"
      %li.nav-item
        = link_to 'Privacy Policy', privacy_path, class: "nav-link"

app/views/shared/_infocard.haml
.card.infocard
  .row
    .col-md-4
      - if @user.image.attached?
        = image_tag @user.image.variant(resize_to_limit: [200, 200])
    .col-md-8
      .card-body
        %h5.card-title
          = @user.name
        %button.btn.btn-outline-info
          = link_to 'See more of this Author', posts_path(user_id: @user.id), data: {icon: 'info', mini: 'true', role: 'button'}

app/views/static_pages/about.html.haml
.row
  .col-md-8.offset-md-2
    %h1 ABOUT US..
    %p The international order has always been in constant change and every day new theories are the base of foreign affairs specialists analysis, either based on classical or contemporary theories. However, due to technological changes and the consolidation of freedom of speech, it has become common for the media and even anyone to comment and express their point of view without being an expert in the field.
    %br
    %p This is the reason why we created this website where foreign affairs students to be able to practice their analysis of the international system based on qualified theories about topics of interest from reliable sources.
    %br
    %p Feel free of questionate every article, share everything you've been learning during your career, and the most important, feel the passion of give a solution to global issues that may change the world forever.
    %br
      =image_tag("https://cuartaposicionblog.files.wordpress.com/2017/12/geopolitica.jpg", class: "img-fluid", alt: "Responsive image", class: "rounded mx-auto d-block img-fluid")

app/views/static_pages/contact.html.haml
.row
  .col-sm-6.offset-sm-3
    .media
      %img(class="mr-3" src="https://ventadeaceromonterrey.files.wordpress.com/2018/06/mail-logo.png?w=512" alt="Generic placeholder image" width="50" height="50")
        .media-body
          %h5.mt-0 Contact
          %br
          %p myviatech@gmail.com

app/views/static_pages/help.html.haml
.row
  .col-md-8.offset-md-2
    %h1 Thanks for join us! Here are some things you can do:
    %br
    %p 1. Complete your profile with the information needed.
    %br
    %p 2. Search for topics you're interested on, for example: realism, covid-19, global order, culture, etc...
    %br
    %p 3. Leave a comment in every Article you read with your opinion so authors can get feedback on their posts.
    %br
    %p 4. Feel free to create your own articles (click "write article" on your profile page) and share your perspectives with all of us.

app/views/static_pages/home.html.haml
.jumbotron
  %h1.display-4 Welcome to my amazing Blog!
  %p.lead This is a blog where you'll find articles about the new global order written by foreign affairs professionals.
  %hr.my-4/
  %p As an international affairs student, you'll have the opportunity to contribute your opinion and share your perspective about new global changes.
  %a.btn.btn-primary.btn-lg{:href => "https://www.foreignaffairs.com/", :role => "button", :target => "_blank"} Learn more
  %span

app/views/static_pages/privacy.html.haml
.col-6.offset-3
  %h4 Click below to read about or privacy policy:
  %br
  %a.btn.btn-warning{:href=> "https://www.websitepolicies.com/policies/view/OMFpvT5v", :role => "button", :target => "_blank"} More info

app/views/static_pages/terms.html.haml
.row
  .col-lg-8.offset-lg-2.p-3.mb-2.bg-light.text-dark
    %h1 Terms and conditions

    %p These terms and conditions ("Terms", "Agreement") are an agreement between Website Operator ("Website Operator", "us", "we" or "our") and you ("User", "you" or "your"). This Agreement sets forth the general terms and conditions of your use of the staging-iablog.herokuapp.com website and any of its products or services (collectively, "Website" or "Services").
    %br

    %h2 Accounts and membership

    %p You must be at least 18 years of age to use this Website. By using this Website and by agreeing to this Agreement you warrant and represent that you are at least 18 years of age. If you create an account on the Website, you are responsible for maintaining the security of your account and you are fully responsible for all activities that occur under the account and any other actions taken in connection with it. We may monitor and review new accounts before you may sign in and use our Services. Providing false contact information of any kind may result in the termination of your account. You must immediately notify us of any unauthorized uses of your account or any other breaches of security. We will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions. We may suspend, disable, or delete your account (or any part thereof) if we determine that you have violated any provision of this Agreement or that your conduct or content would tend to damage our reputation and goodwill. If we delete your account for the foregoing reasons, you may not re-register for our Services. We may block your email address and Internet protocol address to prevent further registration.
    %br

    %h2 Links to other websites

    %p Although this Website may link to other websites, we are not, directly or indirectly, implying any approval, association, sponsorship, endorsement, or affiliation with any linked website, unless specifically stated herein. Some of the links on the Website may be "affiliate links". This means if you click on the link and purchase an item, Website Operator will receive an affiliate commission. We are not responsible for examining or evaluating, and we do not warrant the offerings of, any businesses or individuals or the content of their websites. We do not assume any responsibility or liability for the actions, products, services, and content of any other third-parties. You should carefully review the legal statements and other conditions of use of any website which you access through a link from this Website. Your linking to any other off-site websites is at your own risk.
    %br

    %h2 Prohibited uses

    %p In addition to other terms as set forth in the Agreement, you are prohibited from using the Website or its Content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.
    %br

    %h2 Intellectual property rights

    %p This Agreement does not transfer to you any intellectual property owned by Website Operator or third-parties, and all rights, titles, and interests in and to such property will remain (as between the parties) solely with Website Operator. All trademarks, service marks, graphics and logos used in connection with our Website or Services, are trademarks or registered trademarks of Website Operator or Website Operator licensors. Other trademarks, service marks, graphics and logos used in connection with our Website or Services may be the trademarks of other third-parties. Your use of our Website and Services grants you no right or license to reproduce or otherwise use any Website Operator or third-party trademarks.

    %h2 Limitation of liability

    %p To the fullest extent permitted by applicable law, in no event will Website Operator, its affiliates, officers, directors, employees, agents, suppliers or licensors be liable to any person for (a): any indirect, incidental, special, punitive, cover or consequential damages (including, without limitation, damages for lost profits, revenue, sales, goodwill, use of content, impact on business, business interruption, loss of anticipated savings, loss of business opportunity) however caused, under any theory of liability, including, without limitation, contract, tort, warranty, breach of statutory duty, negligence or otherwise, even if Website Operator has been advised as to the possibility of such damages or could have foreseen such damages. To the maximum extent permitted by applicable law, the aggregate liability of Website Operator and its affiliates, officers, employees, agents, suppliers and licensors, relating to the services will be limited to an amount greater of one dollar or any amounts actually paid in cash by you to Website Operator for the prior one month period prior to the first event or occurrence giving rise to such liability. The limitations and exclusions also apply if this remedy does not fully compensate you for any losses or fails of its essential purpose.

    %h2 Changes and amendments

    %p We reserve the right to modify this Agreement or its policies relating to the Website or Services at any time, effective upon posting of an updated version of this Agreement on the Website. When we do, we will revise the updated date at the bottom of this page. Continued use of the Website after any such changes shall constitute your consent to such changes. Policy was created with https://www.WebsitePolicies.com

    %h2 Acceptance of these terms

    %p You acknowledge that you have read this Agreement and agree to all its terms and conditions. By using the Website or its Services you agree to be bound by this Agreement. If you do not agree to abide by the terms of this Agreement, you are not authorized to use or access the Website and its Services.

    %h2 Contacting us

    %p If you would like to contact us to understand more about this Agreement or wish to contact us concerning any matter relating to it, you may send an email to myviatech@gmail.com

    %h3 This document was last updated on May 21, 2020

app/views/users/edit.haml
.row
  .col-md-6.offset-md-3
    %h2 Edit Profile
    = form_for(@user, class: "edit_form") do |f|
      = render "devise/shared/error_messages", resource: @user
      .form-group
        =f.label :name
        %br
        = f.text_field :name, required: true, class: "form-control"

      .form-group
        =f.label :username
        %br
        = f.text_field :username, required: true, class: "form-control"

      .form-group
        =f.label :location
        %br
        = f.text_field :location, autofocus: true, class: "form-control"
        %br
      .form-group
        =f.label "Profile Photo!"
        =f.file_field :image
        %br
      .actions
        = f.submit "Update", class: "btn btn-primary", method: :update

app/views/users/show.html.haml
.row
  .col-sm-6.offset-sm-3
    %ul.list-group.list-group-flush
      %li.list-group-item
        %p
        EMAIL
        %br
        = @user.email
        %br
      %li.list-group-item
        %p
        NAME
        %br
        = @user.name
        %br
      %li.list-group-item
        %p
        LOCATION
        %br
        = @user.location
        %br
      %li.list-group-item
        %p
        USERNAME
        %br
        = @user.username
        %br
        %span
      %li.list-group-item
        - if @user.image.attached?
          = image_tag @user.image.variant(resize_to_limit: [500, 300])
    #btnPrimary.btn.btn-outline-primary
      = link_to "Edit Profile", edit_user_path(current_user.id), class: "btn.btn-outline-primary"
    %br
    #btnPrimary.btn.btn-outline-danger
      = link_to "Write Article", new_post_path, class: "btn.btn-outline-danger"